images:
- name: csi-driver-lvm
  sourceRepository: https://github.com/metal-stack/csi-driver-lvm
  repository:  ghcr.io/metal-stack/csi-driver-lvm
  tag: "v0.7.0"
- name: csi-driver-lvm-provisioner
  sourceRepository: https://github.com/metal-stack/csi-driver-lvm
  repository:  ghcr.io/metal-stack/csi-driver-lvm-provisioner
  tag: "v0.7.0"
- name: csi-driver-lvm-controller
  sourceRepository: https://github.com/metal-stack/csi-driver-lvm
  repository:  ghcr.io/metal-stack/csi-driver-lvm-controller
  tag: "v0.7.0"
- name: csi-attacher
  sourceRepository: https://github.com/kubernetes-csi/external-attacher
  repository:  registry.k8s.io/sig-storage/csi-attacher
  tag: "v4.4.0"
- name: livenessprobe
  sourceRepository: https://github.com/kubernetes-csi/livenessprobe
  repository:  registry.k8s.io/sig-storage/livenessprobe
  tag: "v2.12.0"
- name: csi-provisioner
  sourceRepository: https://github.com/kubernetes-csi/external-provisioner
  repository: registry.k8s.io/sig-storage/csi-provisioner
  tag: "v5.2.0"
- name: csi-node-driver-registrar
  sourceRepository: https://github.com/kubernetes-csi/node-driver-registrar
  repository:  registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: "v2.9.0"
- name: csi-resizer
  sourceRepository: https://github.com/kubernetes-csi/external-resizer
  repository: registry.k8s.io/sig-storage/csi-resizer
  tag: "v1.13.2"
